apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ftp-service-service
spec:
  endpoints:
    - interval: 15s
      port: metrics
      path: /actuator/prometheus
      scheme: http
  selector:
    matchLabels:
      app: ftp-service-service
